// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpmqzpqfeaokvugworla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwbXF6cHFmZWFva3Z1Z3dvcmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzYzOTcsImV4cCI6MjA2NTA1MjM5N30.IVcuNri-LY1IqADDYiWZt7qSxpw92UQuqSSqJwMp64I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);